[tool.black]
line-length = 119
exclude = '''
(
  /(
      \.mypy_cache
    | \.git
    | migrations
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = 'true'
force_grid_wrap = 0
use_parentheses = 'true'
line_length = 119
# skip = "migrations"
skip = [".mypy_cache", ".git", "*/migrations"]
known_local_folder =["bkuser_core", "bkuser_shell", "bkuser_global", "bkuser_sdk", "bklogin", "backend", "apigateway"]

[tool.flake8]
ignore = "C901,E203,W503"
max-line-length=119
max-complexity=8
format = "pylint"
show_source = "true"
statistics = "true"
count = "true"
exclude = "*migrations*,*.pyc,.git,__pycache__,*/node_modules/*,*/templates_module*,*/bin/*,*/settings/*,*/config/*"

[tool.mypy]
files=["."]
ignore_missing_imports=true
follow_imports="skip"
strict_optional=true
pretty=true
show_error_codes=true

[[tool.mypy.overrides]]
module = [
    "*.migrations.*",
    "*.config.*",
    "*.settings.*",
]
ignore_errors = true

[tool.ruff]
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F", "W", "I", "C90"]
# ignore = ["E741", "F841"]
ignore = ["E741", "F841", "E501"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*/migrations/*",
]

# Same as Black.
line-length = 119

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 12

[tool.ruff.isort]
relative-imports-order = "closest-to-furthest"
# known-local-folder = ["apigateway"]
# known-third-party = ["django"]
