[tool.black]
line-length = 119
exclude = '''
(
  /(
      \.mypy_cache
    | \.git
    | migrations
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = 'true'
force_grid_wrap = 0
use_parentheses = 'true'
line_length = 119
skip = [".mypy_cache", ".git", "*/migrations"]

[tool.flake8]
ignore = "C901,E203,W503"
max-line-length=119
max-complexity=8
format = "pylint"
show_source = "true"
statistics = "true"
count = "true"
exclude = "*migrations*,*.pyc,.git,__pycache__,*/node_modules/*,*/templates_module*,*/bin/*,*/settings/*,*/config/*"

[tool.mypy]
files=["."]
ignore_missing_imports=true
follow_imports="skip"
strict_optional=true
pretty=true
show_error_codes=true

[[tool.mypy.overrides]]
module = [
    "*.migrations.*",
    "*.config.*",
    "*.settings.*",
]
ignore_errors = true
